#!/usr/bin/env bash
# Sets up an nginx server with an html file

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World" > /var/www/html/index.html'
sudo service nginx start
