#!/usr/bin/env bash
# Sets up Nginx server with an html file & redirect & 404 page

# run update and install nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y nginx

# change firewall to allow nginx

sudo ufw allow 'Nginx HTTP'

# echo 'Hello World' into html file

sudo sh -c 'echo "Hello World" > /var/www/html/index.html'

# echo 'Haec pagina non est' into error404.html

sudo sh -c "echo Ceci n\'est pas une page > /var/www/html/error404.html"

# find location in the config file and update 301 redirect

findloc="^\tlocation / {"
update301="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com;\n\t}\n\n\tlocation / {"
sudo sed -i "s@$findloc@$update301@" /etc/nginx/sites-available/default

# update the 404 error

update404="\terror_page 404 /error404.html;\n\n\tadd_header X-Served-By $HOSTNAME;\n\n\tlocation / {"
sudo sed -i "s@$findloc@$update404@" /etc/nginx/sites-available/default

# restart the nginx service

sudo service nginx restart
