#!/usr/bin/env bash
# installs the load balancer HAproxy

# update and upgrade the webserver
sudo apt-get -y update
sudo apt-get -y upgrade

# install haproxy
sudo apt-get -y install haproxy

# create instructions for addition to config file
inst="frontend http_web
\n\tbind *:80
\n\tstats uri /haproxy?stats
\n\tdefault_backend custom_backend
\nbackend custom_backend
\n\tbalance roundrobin
\n\tserver web-01 54.226.72.246:80 check
\n\tserver web-02 52.90.165.36:80 check"

# echo instructions for the config file
echo -e "$inst" | sudo tee -a /etc/haproxy/haproxy.cfg

# checks validity of config file
sudo haproxy -f /etc/haproxy/haproxy.cfg -c

# restart haproxy
sudo service haproxy restart
